#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Vignt\Command;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new Command\StartCommand());
$application->add(new Command\CreateModelCommand());
$application->run();